### ISSUE TITLE
On push broken

### ISSUE THREAD

**Issue by carlosmedrano97** [Lin-Buo-Ren/pre-commit-snap#2]
I have been setting hooks to run only on push, but they don't seem to work, I have tested it with commit and it works fine

here is my .pre-commit-config.yaml

```
default_stages: [push]
repos:
- repo: local
  hooks:
    - id: minitest
      stages: [push]
      entry: api/scripts/run-test.sh
      language: script
      name: minitest
    - id: rubocop
      stages: [push]
      entry: api/scripts/run-rubocop.sh
      language: script
      name: rubocop
```
